#!/bin/sh

#############################################################################
# Version 1.0.1-RELEASE (26-04-2022)
#############################################################################

#############################################################################
# Copyright 2021-2023 Nozel/Sebas Veeke. Licenced under a Creative Commons
# Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# See https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# Contact:
# > e-mail      mail@nozel.org
# > GitHub      nozel-org
#############################################################################

################################################################################
# ERROR FUNCTIONS
################################################################################

error_no_root_privileges() {
    printf "error: must be run with root privileges\n"
    exit 1
}

error_os_not_supported() {
    printf "error: operating system is not supported\n"
    exit 1
}

#############################################################################
# REQUIREMENT FUNCTIONS
#############################################################################

requirement_root() {
    # show error when backupbot isn't run with root privileges
    if [ "$(id -u)" -ne '0' ]; then
        error_no_root_privileges
    fi
}

requirement_os() {
    # show error when freebsd-version cannot be found
    if [ ! "$(command -v freebsd-version)" ]; then
        error_os_not_supported
    fi
}

#############################################################################
# INSTALL FUNCTIONS
#############################################################################

install_uptimebot() {
    # download uptimebot to /usr/local/bin/uptimebot and set ownership (root:wheel) and permissions (555)
    wget -q https://raw.githubusercontent.com/nozel-org/freebsd-uptimebot/master/uptimebot -O /usr/local/bin/uptimebot
    chown root:wheel /usr/local/bin/uptimebot
    chmod 555 /usr/local/bin/uptimebot

    # download uptimebot.conf to /usr/local/etc/uptimebot.conf and set ownership (root:wheel) and permissions (755)
    wget -q https://raw.githubusercontent.com/nozel-org/freebsd-uptimebot/master/uptimebot.conf -O /usr/local/etc/uptimebot.conf
    chown root:wheel /usr/local/etc/uptimebot.conf
    chmod 755 /usr/local/etc/uptimebot.conf

    # download uptimebot_targets.conf to /usr/local/etc/uptimebot_targets.conf and set ownership (root:wheel) and permissions (755)
    wget -q https://raw.githubusercontent.com/nozel-org/freebsd-uptimebot/master/uptimebot_targets.conf -O /usr/local/etc/uptimebot_targets.conf
    chown root:wheel /usr/local/etc/uptimebot_targets.conf
    chmod 755 /usr/local/etc/uptimebot_targets.conf

    # check files
    if [ -f /usr/local/bin/uptimebot ]; then
        printf " [i] uptimebot installed to /usr/local/bin/uptimebot\n"
        FILE_UPTIMEBOT="YES"
    fi
    if [ -f /usr/local/etc/uptimebot.conf ]; then
        printf " [i] uptimebot.conf installed to /usr/local/etc/uptimebot.conf\n"
        FILE_CONF="YES"
    fi
    if [ -f /usr/local/etc/uptimebot_targets.conf ]; then
        printf " [i] uptimebot_targets.conf installed to /usr/local/etc/uptimebot_targets.conf\n"
        FILE_TARGETS="YES"
    fi
    if [ "${FILE_UPTIMEBOT}" = 'YES' ] && [ "${FILE_CONF}" = 'YES' ] && [ "${FILE_TARGETS}" = 'YES' ]; then
        printf " [i] Installation succesful!\n"
    else
        printf " [!] Installation unsuccesful!\n"
    fi
}

requirement_root
requirement_os
install_uptimebot
