#!/bin/sh

#############################################################################
# Version 1.1.0-RELEASE (25-04-2022)
#############################################################################

#############################################################################
# Copyright 2021-2022 Nozel/Sebas Veeke. Licenced under a Creative Commons
# Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# See https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# Contact:
# > e-mail      mail@nozel.org
# > GitHub      nozel-org
#############################################################################

#############################################################################
# VARIABLES
#############################################################################

# uptimebot version
UPTIMEBOT_VERSION='1.1.0'

# check whether uptimebot.conf is available and source it
if [ -f /usr/local/etc/uptimebot.conf ]; then
    # populate all usable variables to have defaults and check validity later on
    UPTIMEBOT_LOG='0'
    UPTIMEBOT_DATABASE='0'
    UPTIMEBOT_DELAY='0'
    PING_LOGONLY='0'
    PING_TELEGRAM='0'
    PORT_LOGONLY='0'
    PORT_TELEGRAM='0'
    HTTP_LOGONLY='0'
    HTTP_TELEGRAM='0'
    DNS_LOGONLY='0'
    DNS_TELEGRAM='0'
    TLS_LOGONLY='0'
    TLS_TELEGRAM='0'
    TOR_LOGONLY='0'
    TOR_TELEGRAM='0'
    ALL_LOGONLY='0'
    ALL_TELEGRAM='0'
    TELEGRAM_TOKEN='0'
    TELEGRAM_CHAT='0'
    TELEGRAM_URL='0'

    # and source backupbot.conf
    . /usr/local/etc/uptimebot.conf

    # populate required variables when they are not set
    if [ "${UPTIMEBOT_LOG}" == '0' ]; then
        UPTIMEBOT_LOG="/var/log/uptimebot.log"
    fi
    if [ "${UPTIMEBOT_DATABASE}" == '0' ]; then
        UPTIMEBOT_DATABASE="/usr/local/etc/uptimebot_targets.conf"
    fi
    if [ "${UPTIMEBOT_DELAY}" == '0' ]; then
        UPTIMEBOT_DELAY='0.5'
    fi
    if [ "${PING_LOGONLY}" == '0' ]; then
        PING_LOGONLY='NO'
    fi
    if [ "${PING_TELEGRAM}" == '0' ]; then
        PING_TELEGRAM='NO'
    fi
    if [ "${PORT_LOGONLY}" == '0' ]; then
        PORT_LOGONLY='NO'
    fi
    if [ "${PORT_TELEGRAM}" == '0' ]; then
        PORT_TELEGRAM='NO'
    fi
    if [ "${HTTP_LOGONLY}" == '0' ]; then
        HTTP_LOGONLY='NO'
    fi
    if [ "${HTTP_TELEGRAM}" == '0' ]; then
        HTTP_TELEGRAM='NO'
    fi
    if [ "${DNS_LOGONLY}" == '0' ]; then
        DNS_LOGONLY='NO'
    fi
    if [ "${DNS_TELEGRAM}" == '0' ]; then
        DNS_TELEGRAM='NO'
    fi
    if [ "${TLS_LOGONLY}" == '0' ]; then
        TLS_LOGONLY='NO'
    fi
    if [ "${TLS_TELEGRAM}" == '0' ]; then
        TLS_TELEGRAM='NO'
    fi
    if [ "${TOR_LOGONLY}" == '0' ]; then
        TOR_LOGONLY='NO'
    fi
    if [ "${TOR_TELEGRAM}" == '0' ]; then
        TOR_TELEGRAM='NO'
    fi
    if [ "${ALL_LOGONLY}" == '0' ]; then
        ALL_LOGONLY='NO'
    fi
    if [ "${ALL_TELEGRAM}" == '0' ]; then
        ALL_TELEGRAM='NO'
    fi
else
    UPTIMEBOT_LOG="/var/log/uptimebot.log"
    UPTIMEBOT_DATABASE='/usr/local/etc/uptimebot_targets.conf'
    UPTIMEBOT_DELAY='0.5'
fi

####################################################################################################
# ARGUMENT HANDLING
####################################################################################################

# populate validation variables with zeros for validation
ARGUMENT_OPTION='0'
ARGUMENT_VERSION='0'
ARGUMENT_HELP='0'
ARGUMENT_FEATURE='0'
ARGUMENT_METHOD='0'
ARGUMENT_PING='0'
ARGUMENT_PORT='0'
ARGUMENT_HTTP='0'
ARGUMENT_DNS='0'
ARGUMENT_TLS='0'
ARGUMENT_TOR='0'
ARGUMENT_ALL='0'
ARGUMENT_LIST='0'
ARGUMENT_LOGONLY='0'
ARGUMENT_CLI='0'
ARGUMENT_TELEGRAM='0'

# watch arguments
while test -n "$1"; do
    case "$1" in
        # options
        --version|-version|version|--v|-v|v)
            ARGUMENT_VERSION='1'
            ARGUMENT_OPTION='1'
            shift
            ;;

        --help|-help|help|--h|-h|h)
            ARGUMENT_HELP='1'
            ARGUMENT_OPTION='1'
            shift
            ;;

        --cron|-cron|cron)
            ARGUMENT_CRON='1'
            ARGUMENT_OPTION='1'
            shift
            ;;

        # features
		--ping|ping)
			ARGUMENT_PING='1'
            ARGUMENT_FEATURE='1'
            shift
            ;;

        --port|port)
			ARGUMENT_PORT='1'
            ARGUMENT_FEATURE='1'
            shift
            ;;

		--http|http)
			ARGUMENT_HTTP='1'
            ARGUMENT_FEATURE='1'
            shift
            ;;

        --dns|dns)
            ARGUMENT_DNS='1'
            ARGUMENT_FEATURE='1'
            shift
            ;;

		--tls|tls)
			ARGUMENT_TLS='1'
            ARGUMENT_FEATURE='1'
            shift
            ;;

		--tor|tor)
			ARGUMENT_TOR='1'
            ARGUMENT_FEATURE='1'
            shift
            ;;

		--all|all)
			ARGUMENT_ALL='1'
            ARGUMENT_FEATURE='1'
            shift
            ;;

        # methods
		--list|list)
			ARGUMENT_LIST='1'
            ARGUMENT_METHOD='1'
            shift
            ;;

		--logonly|logonly|-l|l)
            ARGUMENT_LOGONLY='1'
            ARGUMENT_METHOD='1'
            shift
            ;;

        --cli|cli|-c|c)
            ARGUMENT_CLI='1'
            ARGUMENT_METHOD='1'
            shift
            ;;

        --telegram|telegram|-t|t)
            ARGUMENT_TELEGRAM='1'
            ARGUMENT_METHOD='1'
            shift
            ;;

        # other
        *)
            ARGUMENT_NONE='1'
            shift
            ;;
    esac
done


####################################################################################################
# ERROR FUNCTIONS
####################################################################################################

error_invalid_argument() {
    printf "uptimebot: invalid argument used.\nUse 'uptimebot --help' for a list of valid arguments.\n"
    exit 1
}
error_more_than_one_feature() {
    printf "uptimebot: only one uptimebot feature can be used at a time.\nUse 'uptimebot --help' for a list of valid arguments.\n"
    exit 1
}

error_more_than_one_method() {
    printf "uptimebot: only one uptimebot method can be used at a time.\nUse 'uptimebot --help' for a list of valid arguments.\n"
    exit 1
}

error_method_not_supported() {
    printf "uptimebot: the chosen method isn't supported for the chosen feature.\n"
    exit 1
}

error_no_entries_found() {
	printf "uptimebot: no relevant entries found for this method.\n"
	exit 1
}

####################################################################################################
# REQUIREMENT FUNCTIONS
####################################################################################################

uptimebot_argument_validate() {
    # combine argument categories
    ARGUMENT_FEATURES_COMBINED="$((ARGUMENT_PING + ARGUMENT_PORT + ARGUMENT_HTTP + ARGUMENT_DNS + ARGUMENT_TLS + ARGUMENT_TOR + ARGUMENT_ALL))"
    ARGUMENT_METHOD_COMBINED="$((ARGUMENT_LIST + ARGUMENT_LOGONLY + ARGUMENT_CLI + ARGUMENT_TELEGRAM))"

    if [ "${ARGUMENT_NONE}" = '1' ]; then
        error_invalid_argument
    # validate amount of selected features and return error when more than 1 feature is selected
    elif [ "${ARGUMENT_FEATURES_COMBINED}" -gt '1' ]; then
        error_more_than_one_feature
    # validate amount of selected methods and return error when more than 1 feature is selected
    elif [ "${ARGUMENT_METHOD_COMBINED}" -gt '1' ]; then
        error_more_than_one_method
    fi
}

####################################################################################################
# GENERAL FUNCTIONS
####################################################################################################

option_version() {
    printf "Uptimebot %s\n" "${UPTIMEBOT_VERSION}"
    printf "Copyright (C) 2021-2022 Nozel.\n"
    printf "License CC Attribution-NonCommercial-ShareAlike 4.0 Int.\n\n"
    printf "Written by Sebas Veeke\n"

    # exit when done
    exit 0
}

option_help() {
    printf "Usage:\n"
    printf " uptimebot [feature]... [method]...\n"
    printf " uptimebot [option]...\n\n"
    printf "Features:\n"
    printf " --ping               	Monitor IP address status\n"
    printf " --port                 Monitor port status\n"
	printf " --http               	Monitor HTTP webserver status\n"
	printf " --dns               	Monitor DNS records status\n"
	printf " --tls               	Monitor expiration date for TLS certs\n"
	printf " --tor               	Monitor Tor Relay availability\n"
	printf " --all               	Monitor all configured Features\n\n"
    printf "Methods:\n"
	printf " --list (default)       Output configured rules to cli\n"
	printf " --logonly              Start monitoring and only output to log\n"
    printf " --cli                  Start monitoring and output to cli\n"
    printf " --telegram             Start monitoring and output to Telegram\n\n"
    printf "Options:\n"
    printf " --cron                 Effectuate cron changes from uptimebot config\n"
    printf " --help                 Display this help and exit\n"
    printf " --version              Display version information and exit\n"

    # exit when done
    exit 0
}

option_cron() {
    printf "[1] Removing old uptimebot cronjob\n"
    rm -f /etc/cron.d/uptimebot

    if [ "${PING_LOGONLY}" = 'NO' ] && [ "${PING_TELEGRAM}" = 'NO' ] && \
    [ "${PORT_LOGONLY}" = 'NO' ] && [ "${PORT_TELEGRAM}" = 'NO' ] && \
    [ "${HTTP_LOGONLY}" = 'NO' ] && [ "${HTTP_TELEGRAM}" = 'NO' ] && \
    [ "${DNS_LOGONLY}" = 'NO' ] && [ "${DNS_TELEGRAM}" = 'NO' ] && \
    [ "${TLS_LOGONLY}" = 'NO' ] && [ "${TLS_TELEGRAM}" = 'NO' ] && \
    [ "${TOR_LOGONLY}" = 'NO' ] && [ "${TOR_TELEGRAM}" = 'NO' ] && \
    [ "${ALL_LOGONLY}" = 'NO' ] && [ "${ALL_TELEGRAM}" = 'NO' ]; then
        printf "[2] No automated tasks to add.\n"
        printf "All done!\n"
    else
        printf "[2] Adding configured automated tasks for:\n"
        if [ "${PING_TELEGRAM}" = 'YES' ]; then
            printf "  - ping to Telegram on cron schedule ${PING_CRON}\n"
            printf "${PING_CRON} root /usr/local/bin/uptimebot --ping --telegram\n" >> /etc/cron.d/uptimebot
        elif [ "${PING_LOGONLY}" = 'YES' ]; then
            printf "  - ping to logonly on cron schedule ${PING_CRON}\n"
            printf "${PING_CRON} root /usr/local/bin/uptimebot --ping --logonly\n" >> /etc/cron.d/uptimebot
        fi
        if [ "${PORT_TELEGRAM}" = 'YES' ]; then
            printf "  - port to Telegram on cron schedule ${PORT_CRON}\n"
            printf "${PORT_CRON} root /usr/local/bin/uptimebot --port --telegram\n" >> /etc/cron.d/uptimebot
        elif [ "${PORT_LOGONLY}" = 'YES' ]; then
            printf "  - port to logonly on cron schedule ${PORT_CRON}\n"
            printf "${PORT_CRON} root /usr/local/bin/uptimebot --port --logonly\n" >> /etc/cron.d/uptimebot
        fi
        if [ "${HTTP_TELEGRAM}" = 'YES' ]; then
            printf "  - HTTP to Telegram on cron schedule ${HTTP_CRON}\n"
            printf "${HTTP_CRON} root /usr/local/bin/uptimebot --http --telegram\n" >> /etc/cron.d/uptimebot
        elif [ "${HTTP_LOGONLY}" = 'YES' ]; then
            printf "  - HTTP to logonly on cron schedule ${HTTP_CRON}\n"
            printf "${HTTP_CRON} root /usr/local/bin/uptimebot --http --logonly\n" >> /etc/cron.d/uptimebot
        fi
        if [ "${DNS_TELEGRAM}" = 'YES' ]; then
            printf "  - DNS to Telegram on cron schedule ${DNS_CRON}\n"
            printf "${DNS_CRON} root /usr/local/bin/uptimebot --dns --telegram\n" >> /etc/cron.d/uptimebot
        elif [ "${DNS_LOGONLY}" = 'YES' ]; then
            printf "  - DNS to logonly on cron schedule ${DNS_CRON}\n"
            printf "${DNS_CRON} root /usr/local/bin/uptimebot --dns --logonly\n" >> /etc/cron.d/uptimebot
        fi
        if [ "${TLS_TELEGRAM}" = 'YES' ]; then
            printf "  - TLS to Telegram on cron schedule ${TLS_CRON}\n"
            printf "${TLS_CRON} root /usr/local/bin/uptimebot --tls --telegram\n" >> /etc/cron.d/uptimebot
        elif [ "${TLS_LOGONLY}" = 'YES' ]; then
            printf "  - TLS to logonly on cron schedule ${TLS_CRON}\n"
            printf "${TLS_CRON} root /usr/local/bin/uptimebot --tls --logonly\n" >> /etc/cron.d/uptimebot
        fi
        if [ "${TOR_TELEGRAM}" = 'YES' ]; then
            printf "  - TOR to Telegram on cron schedule ${TOR_CRON}\n"
            printf "${TOR_CRON} root /usr/local/bin/uptimebot --tor --telegram\n" >> /etc/cron.d/uptimebot
        elif [ "${TOR_LOGONLY}" = 'YES' ]; then
            printf "  - TOR to logonly on cron schedule ${TOR_CRON}\n"
            printf "${TOR_CRON} root /usr/local/bin/uptimebot --tor --logonly\n" >> /etc/cron.d/uptimebot
        fi
        if [ "${ALL_TELEGRAM}" = 'YES' ]; then
            printf "  - ALL to Telegram on cron schedule ${ALL_CRON}\n"
            printf "${ALL_CRON} root /usr/local/bin/uptimebot --all --telegram\n" >> /etc/cron.d/uptimebot
        elif [ "${ALL_LOGONLY}" = 'YES' ]; then
            printf "  - ALL to logonly on cron schedule ${ALL_CRON}\n"
            printf "${ALL_CRON} root /usr/local/bin/uptimebot --all --logon\n" >> /etc/cron.d/uptimebot
        fi
        printf "All done! Your new schedule can be found in /etc/cron.d/uptimebot.\n"
    fi

    # exit when done
    exit 0
}

####################################################################################################
# SUPPORT FUNCTIONS
####################################################################################################

slow_down() {
    sleep "${UPTIMEBOT_DELAY}"
}
check_ip_version() {
    if [ "${1}" != "${1#*[0-9].[0-9]}" ]; then
  		IP_VERSION='4'
	elif [ "${1}" != "${1#*:[0-9a-fA-F]}" ]; then
  		IP_VERSION='6'
	else
  		printf "uptimebot: error: IP address not recognized.\n"
	fi
}

send_error_to_log() {
    DATE="$(date +%Y-%m-%d)"
    TIME="$(date +%H:%M:%S)"
    printf "[${DATE}][${TIME}][ERROR]${1} ${2} ${3}\n" >> ${UPTIMEBOT_LOG}
}

send_error_to_telegram() {
    DATE="$(date +%Y-%m-%d)"
    TIME="$(date +%H:%M:%S)"
    TELEGRAM_MESSAGE="$(printf "<b>Outage</b> ${1}\n<code>${2}</code>\n<code>${3}</code>")"
    method_telegram
}

####################################################################################################
# FEATURE FUNCTIONS
####################################################################################################


feature_ping_list() {
	PROTOCOL_PING='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'ping' ]; then
            PROTOCOL_PING='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_PING}" -eq '1' ]; then
        DIVIDER="============================================================================="
		HEADER="\n %-6s %-36s\n"
        FORMAT=" %-6s %-36s\n"
        WIDTH="77"

        printf "${HEADER}" "PING" "IP ADDRESS"
        printf "%${WIDTH}.${WIDTH}s\n" "${DIVIDER}"

        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'ping' ]; then
                IP_ADDRESS="$(echo ${line} | awk '{print $2;}')"
				check_ip_version ${IP_ADDRESS}
                printf "${FORMAT}" "IPv${IP_VERSION}" "${IP_ADDRESS}"
            fi
        done < ${UPTIMEBOT_DATABASE}
    fi
}

feature_port_list() {
    PROTOCOL_PORT4='0'
    PROTOCOL_PORT6='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'port4' ]; then
            PROTOCOL_PORT4='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'port6' ]; then
            PROTOCOL_PORT6='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

    if [ "${PROTOCOL_PORT4}" -eq '1' ] || [ "${PROTOCOL_PORT6}" -eq '1' ]; then
        DIVIDER="============================================================================="
		HEADER="\n %-6s %-36s\n"
        FORMAT=" %-6s %-36s\n"
        WIDTH="77"

        printf "${HEADER}" "PORT" "HOST"
        printf "%${WIDTH}.${WIDTH}s\n" "${DIVIDER}"

        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'port4' ]; then
                HOST="$(echo ${line} | awk '{print $2;}')"
                PORT_NUMBER="$(echo ${line} | awk '{print $3;}')"
				printf "${FORMAT}" "${PORT_NUMBER}" "${HOST}"
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'port6' ]; then
                HOST="$(echo ${line} | awk '{print $2;}')"
                PORT_NUMBER="$(echo ${line} | awk '{print $3;}')"
				printf "${FORMAT}" "${PORT_NUMBER}" "${HOST}"
            fi
        done < ${UPTIMEBOT_DATABASE}
    fi
}

feature_http_list() {
	PROTOCOL_HTTP4='0'
    PROTOCOL_HTTP6='0'
    PROTOCOL_HTTPS4='0'
    PROTOCOL_HTTPS6='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'http4' ]; then
            PROTOCOL_HTTP4='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'http6' ]; then
            PROTOCOL_HTTP6='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'https4' ]; then
            PROTOCOL_HTTPS4='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'https6' ]; then
            PROTOCOL_HTTPS6='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_HTTP4}" -eq '1' ] || [ "${PROTOCOL_HTTP6}" -eq '1' ] || \
	[ "${PROTOCOL_HTTPS4}" -eq '1' ] || [ "${PROTOCOL_HTTPS6}" -eq '1' ]; then
        DIVIDER="============================================================================="
        HEADER="\n %-6s %-36s\n"
        FORMAT=" %-6s %-36s\n"
        WIDTH="77"
        printf "${HEADER}" "HTTP" "HOST"
        printf "%${WIDTH}.${WIDTH}s\n" "${DIVIDER}"
        if [ "${PROTOCOL_HTTP4}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'http4' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    printf "${FORMAT}" "IPv4" "http://${DOMAIN_NAME}"
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_HTTP6}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'http6' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    printf "${FORMAT}" "IPv6" "https://${DOMAIN_NAME}"
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_HTTPS4}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'https4' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    printf "${FORMAT}" "IPv4" "http://${DOMAIN_NAME}"
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_HTTPS6}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'https6' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    printf "${FORMAT}" "IPv6" "https://${DOMAIN_NAME}"
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
    fi
}

feature_dns_list() {
	PROTOCOL_DNS_A='0'
    PROTOCOL_DNS_AAAA='0'
	PROTOCOL_DNS_CNAME='0'
    PROTOCOL_DNS_TXT='0'
    PROTOCOL_DNS_MX='0'
    PROTOCOL_DNS_NS='0'
    PROTOCOL_DNS_SOA='0'
    PROTOCOL_DNS_PTR='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'a' ]; then
            PROTOCOL_DNS_A='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'aaaa' ]; then
            PROTOCOL_DNS_AAAA='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'cname' ]; then
            PROTOCOL_DNS_CNAME='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'txt' ]; then
            PROTOCOL_DNS_TXT='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'mx' ]; then
            PROTOCOL_DNS_MX='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'ns' ]; then
            PROTOCOL_DNS_NS='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'soa' ]; then
            PROTOCOL_DNS_SOA='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'ptr' ]; then
            PROTOCOL_DNS_PTR='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_DNS_A}" -eq '1' ] || [ "${PROTOCOL_DNS_AAAA}" -eq '1' ] || [ "${PROTOCOL_DNS_CNAME}" -eq '1' ] || [ "${PROTOCOL_DNS_TXT}" -eq '1' ] || \
	[ "${PROTOCOL_DNS_MX}" -eq '1' ] || [ "${PROTOCOL_DNS_NS}" -eq '1' ] || [ "${PROTOCOL_DNS_SOA}" -eq '1' ] || [ "${PROTOCOL_DNS_PTR}" -eq '1' ]; then
        DIVIDER="============================================================================="
        HEADER="\n %-6s %-36s %-36s\n"
        FORMAT=" %-6s %-36s %-36s\n"
        WIDTH="77"
        printf "${HEADER}" "DNS" "DOMAIN NAME" "ENTRY"
        printf "%${WIDTH}.${WIDTH}s\n" "${DIVIDER}"
		if [ "${PROTOCOL_DNS_A}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'a' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    ENTRY="$(echo ${line} | awk '{print $3;}')"
                    printf "${FORMAT}" "A" "${DOMAIN_NAME}" "${ENTRY}"
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_AAAA}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'aaaa' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    ENTRY="$(echo ${line} | awk '{print $3;}')"
                    printf "${FORMAT}" "AAAA" "${DOMAIN_NAME}" "${ENTRY}"
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_CNAME}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'cname' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    ENTRY="$(echo ${line} | awk '{print $3;}')"
                    printf "${FORMAT}" "CNAME" "${DOMAIN_NAME}" "${ENTRY}"
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_TXT}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'txt' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    ENTRY="$(echo ${line} | awk '{print $3;}')"
                    printf "${FORMAT}" "TXT" "${DOMAIN_NAME}" "${ENTRY}"
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_MX}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'mx' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    ENTRY="$(echo ${line} | awk '{print $3;}')"
                    printf "${FORMAT}" "MX" "${DOMAIN_NAME}" "${ENTRY}"
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_NS}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'ns' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    ENTRY="$(echo ${line} | awk '{print $3;}')"
                    printf "${FORMAT}" "NS" "${DOMAIN_NAME}" "${ENTRY}"
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_SOA}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'soa' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    ENTRY="$(echo ${line} | awk '{print $3;}')"
                    printf "${FORMAT}" "SOA" "${DOMAIN_NAME}" "${ENTRY}"
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_PTR}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'ptr' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    ENTRY="$(echo ${line} | awk '{print $3;}')"
                    printf "${FORMAT}" "PTR" "${DOMAIN_NAME}" "${ENTRY}"
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
    fi
}

feature_tls_list() {
	PROTOCOL_TLS='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'tls' ]; then
            PROTOCOL_TLS='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_TLS}" -eq '1' ]; then
		DIVIDER="============================================================================="
        HEADER="\n %-6s %-8s\n"
        FORMAT=" %-6s %-8s\n"
        WIDTH="77"
		printf "${HEADER}" "TLS" "DOMAIN NAME"
        printf "%${WIDTH}.${WIDTH}s\n" "${DIVIDER}"
		if [ "${PROTOCOL_TLS}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'tls' ]; then
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    printf "${FORMAT}" "TLS" "${DOMAIN_NAME}"
                fi
            done < ${UPTIMEBOT_DATABASE}
		fi
	fi
}

feature_tor_list() {
	echo 'wip'
}

feature_all_list() {
	feature_ping_list
    feature_port_list
	feature_http_list
	feature_dns_list
	feature_tls_list
	feature_tor_list
}

feature_ping_logonly() {
	PROTOCOL_PING='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'ping' ]; then
            PROTOCOL_PING='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_PING}" -eq '1' ]; then
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'ping' ]; then
                slow_down
                IP_ADDRESS="$(echo ${line} | awk '{print $2;}')"
				check_ip_version ${IP_ADDRESS}
				if [ "${IP_VERSION}" -eq '4' ]; then
					if ! ping -q -c1 -t2 ${IP_ADDRESS} > /dev/null 2>&1; then
                        if ! ping -q -c1 ${IP_ADDRESS} > /dev/null 2>&1; then
                            send_error_to_log "[PING][IPv4]" "${IP_ADDRESS}"
                        fi
                    fi
                elif [ "${IP_VERSION}" -eq '6' ]; then
					if ! ping6 -q -c1 -t2 ${IP_ADDRESS} > /dev/null 2>&1; then
                        if ! ping6 -q -c1 ${IP_ADDRESS} > /dev/null 2>&1; then
                            send_error_to_log "[PING][IPv6]" "${IP_ADDRESS}"
                        fi
                    fi
				fi
            fi
        done < ${UPTIMEBOT_DATABASE}
    fi
}

feature_port_logonly() {
    PROTOCOL_PORT4='0'
    PROTOCOL_PORT6='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'port4' ]; then
            PROTOCOL_PORT4='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'port6' ]; then
            PROTOCOL_PORT6='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

    if [ "${PROTOCOL_PORT4}" -eq '1' ] || [ "${PROTOCOL_PORT6}" -eq '1' ]; then
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'port4' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                PORT_NUMBER="$(echo ${line} | awk '{print $3;}')"
                if ! nc -4zw2 ${HOST} ${PORT_NUMBER} > /dev/null 2>&1; then
                    send_error_to_log "[PORT][${PORT_NUMBER}][IPv4]" "${HOST}:${PORT_NUMBER}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'port6' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                PORT_NUMBER="$(echo ${line} | awk '{print $3;}')"
                if ! nc -6zw2 ${HOST} ${PORT_NUMBER} > /dev/null 2>&1; then
                    send_error_to_log "[PORT][${PORT_NUMBER}][IPv6]" "${HOST}:${PORT_NUMBER}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
    fi
}

feature_http_logonly() {
	PROTOCOL_HTTP4='0'
    PROTOCOL_HTTP6='0'
    PROTOCOL_HTTPS4='0'
    PROTOCOL_HTTPS6='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'http4' ]; then
            PROTOCOL_HTTP4='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'http6' ]; then
            PROTOCOL_HTTP6='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'https4' ]; then
            PROTOCOL_HTTPS4='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'https6' ]; then
            PROTOCOL_HTTPS6='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_HTTP4}" -eq '1' ] || [ "${PROTOCOL_HTTP6}" -eq '1' ] || \
	[ "${PROTOCOL_HTTPS4}" -eq '1' ] || [ "${PROTOCOL_HTTPS6}" -eq '1' ]; then
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'http4' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                if !  curl -I -4 ${HOST} 2>&1 | grep -w "200 OK\|301 Moved Permanently" > /dev/null; then
                    send_error_to_log "[HTTP][IPv4]" "http://${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'http6' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                if !  curl -I -6 ${HOST} 2>&1 | grep -w "200 OK\|301 Moved Permanently" > /dev/null; then
                    send_error_to_log "[HTTP][IPv6]" "https://${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'https4' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                if !  curl -I -4 ${HOST} 2>&1 | grep -w "200 OK\|301 Moved Permanently" > /dev/null; then
                    send_error_to_log "[HTTPS][IPv4]" "http://${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'https6' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                if !  curl -I -6 ${HOST} 2>&1 | grep -w "200 OK\|301 Moved Permanently" > /dev/null; then
                    send_error_to_log "[HTTPS][IPv6]" "https://${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
    fi
}

feature_dns_logonly() {
	PROTOCOL_DNS_A='0'
    PROTOCOL_DNS_AAAA='0'
	PROTOCOL_DNS_CNAME='0'
    PROTOCOL_DNS_TXT='0'
    PROTOCOL_DNS_MX='0'
    PROTOCOL_DNS_NS='0'
    PROTOCOL_DNS_SOA='0'
    PROTOCOL_DNS_PTR='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'a' ]; then
            PROTOCOL_DNS_A='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'aaaa' ]; then
            PROTOCOL_DNS_AAAA='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'cname' ]; then
            PROTOCOL_DNS_CNAME='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'txt' ]; then
            PROTOCOL_DNS_TXT='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'mx' ]; then
            PROTOCOL_DNS_MX='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'ns' ]; then
            PROTOCOL_DNS_NS='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'soa' ]; then
            PROTOCOL_DNS_SOA='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'ptr' ]; then
            PROTOCOL_DNS_PTR='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_DNS_A}" -eq '1' ] || [ "${PROTOCOL_DNS_AAAA}" -eq '1' ] || [ "${PROTOCOL_DNS_CNAME}" -eq '1' ] || [ "${PROTOCOL_DNS_TXT}" -eq '1' ] || \
	[ "${PROTOCOL_DNS_MX}" -eq '1' ] || [ "${PROTOCOL_DNS_NS}" -eq '1' ] || [ "${PROTOCOL_DNS_SOA}" -eq '1' ] || [ "${PROTOCOL_DNS_PTR}" -eq '1' ]; then
		if [ "${PROTOCOL_DNS_A}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'a' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t a ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        DNS_VALUE="$(host -t a ${DOMAIN_NAME})"
                        send_error_to_log "[DNS][A]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_AAAA}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'aaaa' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t aaaa ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][AAAA]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_CNAME}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'cname' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t cname ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][CNAME]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_TXT}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'txt' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t txt ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][TXT]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_MX}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'mx' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t mx ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][MX]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_NS}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'ns' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t ns ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][NS]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_SOA}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'soa' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t soa ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][SOA]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_PTR}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'ptr' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t ptr ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][PTR]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
    fi
}

feature_tls_logonly() {
	echo ''
}

feature_tor_logonly() {
	echo ''
}

feature_all_logonly() {
	feature_ping_logonly
    feature_port_logonly
    feature_http_logonly
    feature_dns_logonly
    feature_tls_logonly
    feature_tor_logonly
}

feature_ping_cli() {
	PROTOCOL_PING='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'ping' ]; then
            PROTOCOL_PING='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_PING}" -eq '1' ]; then
        DIVIDER="============================================================================="
        HEADER="\n %-5s %-8s %-8s %-36s\n"
        FORMAT=" %-5s %-8s %-8s %-36s\n"
        WIDTH="77"
        printf "${HEADER}" "PING" "STATUS" "IP" "IP ADDRESS"
        printf "%${WIDTH}.${WIDTH}s\n" "${DIVIDER}"

        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'ping' ]; then
                slow_down
                IP_ADDRESS="$(echo ${line} | awk '{print $2;}')"
				check_ip_version ${IP_ADDRESS}
				if [ "${IP_VERSION}" -eq '4' ]; then
					if ! ping -q -c1 -t2 ${IP_ADDRESS} > /dev/null 2>&1; then
                        if ! ping -q -c1 -t2 ${IP_ADDRESS} > /dev/null 2>&1; then
                            printf "${FORMAT}" "[!]" "DOWN" "IPv4" "${IP_ADDRESS}"
                            send_error_to_log "[PING][IPv4]" ${IP_ADDRESS}
                        fi
                    else
                        printf "${FORMAT}" "[i]" "UP" "IPv4" "${IP_ADDRESS}"
                    fi
                elif [ "${IP_VERSION}" -eq '6' ]; then
					if ! ping6 -q -c1 -t2 ${IP_ADDRESS} > /dev/null 2>&1; then
                        if ! ping6 -q -c1 -t2 ${IP_ADDRESS} > /dev/null 2>&1; then
                            printf "${FORMAT}" "[!]" "DOWN" "IPv6" "${IP_ADDRESS}"
                            send_error_to_log "[PING][IPv6]" ${IP_ADDRESS}
                        fi
                    else
                        printf "${FORMAT}" "[i]" "UP" "IPv6" "${IP_ADDRESS}"
                    fi
				fi
            fi
        done < ${UPTIMEBOT_DATABASE}
    fi
}

feature_port_cli() {
    PROTOCOL_PORT4='0'
    PROTOCOL_PORT6='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'port4' ]; then
            PROTOCOL_PORT4='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'port6' ]; then
            PROTOCOL_PORT6='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

    if [ "${PROTOCOL_PORT4}" -eq '1' ] || [ "${PROTOCOL_PORT6}" -eq '1' ]; then
        DIVIDER="============================================================================="
        HEADER="\n %-5s %-8s %-8s %-36s\n"
        FORMAT=" %-5s %-8s %-8s %-36s\n"
        WIDTH="77"
        printf "${HEADER}" "PORT" "STATUS" "NR" "HOST"
        printf "%${WIDTH}.${WIDTH}s\n" "${DIVIDER}"

        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'port4' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                PORT_NUMBER="$(echo ${line} | awk '{print $3;}')"
                if ! nc -4zw2 ${HOST} ${PORT_NUMBER} > /dev/null 2>&1; then
                    printf "${FORMAT}" "[!]" "DOWN" "${PORT_NUMBER}" "${HOST}"
                    send_error_to_log "[PORT][${PORT_NUMBER}][IPv4]" "${HOST}:${PORT_NUMBER}"
                else
                    printf "${FORMAT}" "[i]" "UP" "${PORT_NUMBER}" "${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'port6' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                PORT_NUMBER="$(echo ${line} | awk '{print $3;}')"
                if ! nc -6zw2 ${HOST} ${PORT_NUMBER} > /dev/null 2>&1; then
                    printf "${FORMAT}" "[!]" "DOWN" "${PORT_NUMBER}" "${HOST}"
                    send_error_to_log "[PORT][${PORT_NUMBER}][IPv6]" "${HOST}:${PORT_NUMBER}"
                else
                    printf "${FORMAT}" "[i]" "UP" "${PORT_NUMBER}" "${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
    fi
}

feature_http_cli() {
	PROTOCOL_HTTP4='0'
    PROTOCOL_HTTP6='0'
    PROTOCOL_HTTPS4='0'
    PROTOCOL_HTTPS6='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'http4' ]; then
            PROTOCOL_HTTP4='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'http6' ]; then
            PROTOCOL_HTTP6='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'https4' ]; then
            PROTOCOL_HTTPS4='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'https6' ]; then
            PROTOCOL_HTTPS6='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_HTTP4}" -eq '1' ] || [ "${PROTOCOL_HTTP6}" -eq '1' ] || \
	[ "${PROTOCOL_HTTPS4}" -eq '1' ] || [ "${PROTOCOL_HTTPS6}" -eq '1' ]; then
        DIVIDER="============================================================================="
        HEADER="\n %-5s %-8s %-8s %-36s\n"
        FORMAT=" %-5s %-8s %-8s %-36s\n"
        WIDTH="77"
        printf "${HEADER}" "HTTP" "STATUS" "IP" "HOST"
        printf "%${WIDTH}.${WIDTH}s\n" "${DIVIDER}"

        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'http4' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                if !  curl -I -4 ${HOST} 2>&1 | grep -w "200 OK\|301 Moved Permanently" > /dev/null; then
                    printf "${FORMAT}" "[!]" "DOWN" "IPv4" "http://${HOST}"
                    send_error_to_log "[HTTP][IPv4]" "http://${HOST}"
                else
                    printf "${FORMAT}" "[i]" "UP" "IPv4" "http://${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'http6' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                if !  curl -I -6 ${HOST} 2>&1 | grep -w "200 OK\|301 Moved Permanently" > /dev/null; then
                    printf "${FORMAT}" "[!]" "DOWN" "IPv6" "http://${HOST}"
                    send_error_to_log "[HTTP][IPv6]" "http://${HOST}"
                else
                    printf "${FORMAT}" "[i]" "UP" "IPv6" "http://${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'https4' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                if !  curl -I -4 ${HOST} 2>&1 | grep -w "200 OK\|301 Moved Permanently" > /dev/null; then
                    printf "${FORMAT}" "[!]" "DOWN" "IPv4" "https://${HOST}"
                    send_error_to_log "[HTTPS][IPv4]" "https://${HOST}"
                else
                    printf "${FORMAT}" "[i]" "UP" "IPv4" "https://${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'https6' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                if !  curl -I -6 ${HOST} 2>&1 | grep -w "200 OK\|301 Moved Permanently" > /dev/null; then
                    printf "${FORMAT}" "[!]" "DOWN" "IPv6" "https://${HOST}"
                    send_error_to_log "[HTTPS][IPv6]" "https://${HOST}"
                else
                    printf "${FORMAT}" "[i]" "UP" "IPv6" "https://${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
    fi
}

feature_dns_cli() {
	PROTOCOL_DNS_A='0'
    PROTOCOL_DNS_AAAA='0'
	PROTOCOL_DNS_CNAME='0'
    PROTOCOL_DNS_TXT='0'
    PROTOCOL_DNS_MX='0'
    PROTOCOL_DNS_NS='0'
    PROTOCOL_DNS_SOA='0'
    PROTOCOL_DNS_PTR='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'a' ]; then
            PROTOCOL_DNS_A='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'aaaa' ]; then
            PROTOCOL_DNS_AAAA='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'cname' ]; then
            PROTOCOL_DNS_CNAME='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'txt' ]; then
            PROTOCOL_DNS_TXT='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'mx' ]; then
            PROTOCOL_DNS_MX='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'ns' ]; then
            PROTOCOL_DNS_NS='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'soa' ]; then
            PROTOCOL_DNS_SOA='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'ptr' ]; then
            PROTOCOL_DNS_PTR='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_DNS_A}" -eq '1' ] || [ "${PROTOCOL_DNS_AAAA}" -eq '1' ] || [ "${PROTOCOL_DNS_CNAME}" -eq '1' ] || [ "${PROTOCOL_DNS_TXT}" -eq '1' ] || \
	[ "${PROTOCOL_DNS_MX}" -eq '1' ] || [ "${PROTOCOL_DNS_NS}" -eq '1' ] || [ "${PROTOCOL_DNS_SOA}" -eq '1' ] || [ "${PROTOCOL_DNS_PTR}" -eq '1' ]; then
        DIVIDER="============================================================================="
        HEADER="\n %-5s %-8s %-8s %-36s %-20s\n"
        FORMAT=" %-5s %-8s %-8s %-36s %-20s\n"
        WIDTH="77"
        printf "${HEADER}" "DNS" "STATUS" "TYPE" "DOMAIN NAME" "DNS CHECK"
        printf "%${WIDTH}.${WIDTH}s\n" "${DIVIDER}"
		if [ "${PROTOCOL_DNS_A}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'a' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t a ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        DNS_VALUE="$(host -t a ${DOMAIN_NAME})"
                        printf "${FORMAT}" "[!]" "ERROR" "A" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_log "[DNS][A]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    else
                        printf "${FORMAT}" "[i]" "MATCH" "A" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_AAAA}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'aaaa' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t aaaa ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        printf "${FORMAT}" "[!]" "ERROR" "AAAA" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_log "[DNS][AAAA]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    else
                        printf "${FORMAT}" "[i]" "MATCH" "AAAA" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_CNAME}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'cname' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t cname ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        printf "${FORMAT}" "[!]" "ERROR" "CNAME" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_log "[DNS][CNAME]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    else
                        printf "${FORMAT}" "[i]" "MATCH" "CNAME" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_TXT}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'txt' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t txt ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        printf "${FORMAT}" "[!]" "ERROR" "TXT" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_log "[DNS][TXT]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    else
                        printf "${FORMAT}" "[i]" "MATCH" "TXT" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_MX}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'mx' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t mx ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        printf "${FORMAT}" "[!]" "ERROR" "MX" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_log "[DNS][MX]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    else
                        printf "${FORMAT}" "[i]" "MATCH" "MX" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_NS}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'ns' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t ns ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        printf "${FORMAT}" "[!]" "ERROR" "NS" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_log "[DNS][NS]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    else
                        printf "${FORMAT}" "[i]" "MATCH" "NS" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_SOA}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'soa' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t soa ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        printf "${FORMAT}" "[!]" "ERROR" "SOA" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_log "[DNS][SOA]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    else
                        printf "${FORMAT}" "[i]" "MATCH" "SOA" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_PTR}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'ptr' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t ptr ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        printf "${FORMAT}" "[!]" "ERROR" "PTR" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_log "[DNS][PTR]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    else
                        printf "${FORMAT}" "[i]" "MATCH" "PTR" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
    fi
}

feature_tls_cli() {
	echo ''
}

feature_tor_cli() {
	echo ''
}

feature_all_cli() {
	feature_ping_cli
    feature_port_cli
    feature_http_cli
    feature_dns_cli
    feature_tls_cli
    feature_tor_cli
}

feature_ping_telegram() {
	PROTOCOL_PING='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'ping' ]; then
            PROTOCOL_PING='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_PING}" -eq '1' ]; then
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'ping' ]; then
                slow_down
                IP_ADDRESS="$(echo ${line} | awk '{print $2;}')"
				check_ip_version ${IP_ADDRESS}
				if [ "${IP_VERSION}" -eq '4' ]; then
					if ! ping -q -c1 -t2 ${IP_ADDRESS} > /dev/null 2>&1; then
                        if ! ping -q -c1 -t2 ${IP_ADDRESS} > /dev/null 2>&1; then
                            send_error_to_log "[PING][IPv4]" "${IP_ADDRESS}"
                            send_error_to_telegram "[PING][IPv4]" "${IP_ADDRESS}"
                        fi
                    fi
                elif [ "${IP_VERSION}" -eq '6' ]; then
					if ! ping6 -q -c1 -t2 ${IP_ADDRESS} > /dev/null 2>&1; then
                        if ! ping6 -q -c1 -t2 ${IP_ADDRESS} > /dev/null 2>&1; then
                            send_error_to_log "[PING][IPv6]" "${IP_ADDRESS}"
                            send_error_to_telegram "[PING][IPv6]" "${IP_ADDRESS}"
                        fi
                    fi
				fi
            fi
        done < ${UPTIMEBOT_DATABASE}
    fi
}

feature_port_telegram() {
    PROTOCOL_PORT4='0'
    PROTOCOL_PORT6='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'port4' ]; then
            PROTOCOL_PORT4='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'port6' ]; then
            PROTOCOL_PORT6='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

    if [ "${PROTOCOL_PORT4}" -eq '1' ] || [ "${PROTOCOL_PORT6}" -eq '1' ]; then
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'port4' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                PORT_NUMBER="$(echo ${line} | awk '{print $3;}')"
                if ! nc -4zw2 ${HOST} ${PORT_NUMBER} > /dev/null 2>&1; then
                    send_error_to_log "[PORT][${PORT_NUMBER}][IPv4]" "${HOST}:${PORT_NUMBER}"
                    send_error_to_telegram "[PORT][IPv4]" "${HOST}:${PORT_NUMBER}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'port6' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                PORT_NUMBER="$(echo ${line} | awk '{print $3;}')"
                if ! nc -6zw2 ${HOST} ${PORT_NUMBER} > /dev/null 2>&1; then
                    send_error_to_log "[PORT][${PORT_NUMBER}][IPv6]" "${HOST}:${PORT_NUMBER}"
                    send_error_to_telegram "[PORT][IPv6]" "${HOST}:${PORT_NUMBER}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
    fi
}

feature_http_telegram() {
	PROTOCOL_HTTP4='0'
    PROTOCOL_HTTP6='0'
    PROTOCOL_HTTPS4='0'
    PROTOCOL_HTTPS6='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'http4' ]; then
            PROTOCOL_HTTP4='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'http6' ]; then
            PROTOCOL_HTTP6='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'https4' ]; then
            PROTOCOL_HTTPS4='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'https6' ]; then
            PROTOCOL_HTTPS6='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_HTTP4}" -eq '1' ] || [ "${PROTOCOL_HTTP6}" -eq '1' ] || \
	[ "${PROTOCOL_HTTPS4}" -eq '1' ] || [ "${PROTOCOL_HTTPS6}" -eq '1' ]; then
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'http4' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                if !  curl -I -4 ${HOST} 2>&1 | grep -w "200 OK\|301 Moved Permanently" > /dev/null; then
                    send_error_to_log "[HTTP][IPv4]" "http://${HOST}"
                    send_error_to_telegram "[HTTP][IPv4]" "http://${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'http6' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                if !  curl -I -6 ${HOST} 2>&1 | grep -w "200 OK\|301 Moved Permanently" > /dev/null; then
                    send_error_to_log http "[HTTP][IPv6]" "http://${HOST}"
                    send_error_to_telegram HTTP "[HTTP][IPv6]" "http://${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'https4' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                if !  curl -I -4 ${HOST} 2>&1 | grep -w "200 OK\|301 Moved Permanently" > /dev/null; then
                    send_error_to_log "[HTTPS][IPv4]" "https://${HOST}"
                    send_error_to_telegram "[HTTPS][IPv4]" "https://${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
        while read line; do
            if [ "$(echo ${line} | awk '{print $1;}')" == 'https6' ]; then
                slow_down
                HOST="$(echo ${line} | awk '{print $2;}')"
                if !  curl -I -6 ${HOST} 2>&1 | grep -w "200 OK\|301 Moved Permanently" > /dev/null; then
                    send_error_to_log "[HTTPS][IPv6]" "https://${HOST}"
                    send_error_to_telegram "[HTTPS][IPv6]" "https://${HOST}"
                fi
            fi
        done < ${UPTIMEBOT_DATABASE}
    fi
}

feature_dns_telegram() {
	PROTOCOL_DNS_A='0'
    PROTOCOL_DNS_AAAA='0'
	PROTOCOL_DNS_CNAME='0'
    PROTOCOL_DNS_TXT='0'
    PROTOCOL_DNS_MX='0'
    PROTOCOL_DNS_NS='0'
    PROTOCOL_DNS_SOA='0'
    PROTOCOL_DNS_PTR='0'

	while read line; do
        if [ "$(echo ${line} | awk '{print $1;}')" == 'a' ]; then
            PROTOCOL_DNS_A='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'aaaa' ]; then
            PROTOCOL_DNS_AAAA='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'cname' ]; then
            PROTOCOL_DNS_CNAME='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'txt' ]; then
            PROTOCOL_DNS_TXT='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'mx' ]; then
            PROTOCOL_DNS_MX='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'ns' ]; then
            PROTOCOL_DNS_NS='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'soa' ]; then
            PROTOCOL_DNS_SOA='1'
        fi
        if [ "$(echo ${line} | awk '{print $1;}')" == 'ptr' ]; then
            PROTOCOL_DNS_PTR='1'
        fi
    done < ${UPTIMEBOT_DATABASE}

	if [ "${PROTOCOL_DNS_A}" -eq '1' ] || [ "${PROTOCOL_DNS_AAAA}" -eq '1' ] || [ "${PROTOCOL_DNS_CNAME}" -eq '1' ] || [ "${PROTOCOL_DNS_TXT}" -eq '1' ] || \
	[ "${PROTOCOL_DNS_MX}" -eq '1' ] || [ "${PROTOCOL_DNS_NS}" -eq '1' ] || [ "${PROTOCOL_DNS_SOA}" -eq '1' ] || [ "${PROTOCOL_DNS_PTR}" -eq '1' ]; then
		if [ "${PROTOCOL_DNS_A}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'a' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t a ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        DNS_VALUE="$(host -t a ${DOMAIN_NAME})"
                        send_error_to_log "[DNS][A]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_telegram "[DNS][A]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_AAAA}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'aaaa' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t aaaa ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][AAAA]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_telegram "[DNS][AAAA]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_CNAME}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'cname' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t cname ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][CNAME]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_telegram "[DNS][CNAME]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_TXT}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'txt' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t txt ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][TXT]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_telegram "[DNS][TXT]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_MX}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'mx' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t mx ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][MX]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_telegram "[DNS][MX]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_NS}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'ns' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t ns ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][NS]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_telegram "[DNS][NS]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_SOA}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'soa' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t soa ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][SOA]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_telegram "[DNS][SOA]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
        if [ "${PROTOCOL_DNS_PTR}" -eq '1' ]; then
            while read line; do
                if [ "$(echo ${line} | awk '{print $1;}')" == 'ptr' ]; then
                    slow_down
                    DOMAIN_NAME="$(echo ${line} | awk '{print $2;}')"
                    DNS_CHECK="$(echo ${line} | awk '{print $3;}')"
                    if ! host -t ptr ${DOMAIN_NAME} 2>&1 | grep "${DNS_CHECK}" > /dev/null; then
                        send_error_to_log "[DNS][PTR]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                        send_error_to_telegram "[DNS][PTR]" "${DOMAIN_NAME}" "${DNS_CHECK}"
                    fi
                fi
            done < ${UPTIMEBOT_DATABASE}
        fi
    fi
}

feature_tls_telegram() {
	printf ''
}

feature_tor_telegram() {
	printf ''
}

feature_all_telegram() {
	feature_ping_telegram
    feature_port_telegram
    feature_http_telegram
    feature_dns_telegram
    feature_tls_telegram
    feature_tor_telegram
}

####################################################################################################
# METHOD FUNCTIONS
####################################################################################################

method_telegram() {
    # create payload for Telegram
    TELEGRAM_PAYLOAD="chat_id=${TELEGRAM_CHAT}&text=${TELEGRAM_MESSAGE}&parse_mode=HTML&disable_web_page_preview=true"

    # sent payload to Telegram API and exit
    curl --silent --max-time 10 --retry 5 --retry-delay 2 --retry-max-time 10 -d "${TELEGRAM_PAYLOAD}" "${TELEGRAM_URL}" > /dev/null 2>&1 &
}

####################################################################################################
# MAIN FUNCTIONS
####################################################################################################

uptimebot_main() {
    # validate arguments
    uptimebot_argument_validate

    # when both a feature and method cli are given
	if [ "${ARGUMENT_PING}" = '1' ] && [ "${ARGUMENT_LIST}" = '1' ]; then
		feature_ping_list
    elif [ "${ARGUMENT_PORT}" = '1' ] && [ "${ARGUMENT_LIST}" = '1' ]; then
		feature_port_list
	elif [ "${ARGUMENT_HTTP}" = '1' ] && [ "${ARGUMENT_LIST}" = '1' ]; then
		feature_http_list
	elif [ "${ARGUMENT_DNS}" = '1' ] && [ "${ARGUMENT_LIST}" = '1' ]; then
		feature_dns_list
	elif [ "${ARGUMENT_TLS}" = '1' ] && [ "${ARGUMENT_LIST}" = '1' ]; then
		feature_tls_list
	elif [ "${ARGUMENT_TOR}" = '1' ] && [ "${ARGUMENT_LIST}" = '1' ]; then
		feature_tor_list
	elif [ "${ARGUMENT_ALL}" = '1' ] && [ "${ARGUMENT_LIST}" = '1' ]; then
		feature_all_list
    elif [ "${ARGUMENT_PING}" = '1' ] && [ "${ARGUMENT_LOGONLY}" = '1' ]; then
		feature_ping_logonly
    elif [ "${ARGUMENT_PORT}" = '1' ] && [ "${ARGUMENT_LOGONLY}" = '1' ]; then
		feature_port_logonly
	elif [ "${ARGUMENT_HTTP}" = '1' ] && [ "${ARGUMENT_LOGONLY}" = '1' ]; then
		feature_http_logonly
	elif [ "${ARGUMENT_DNS}" = '1' ] && [ "${ARGUMENT_LOGONLY}" = '1' ]; then
		feature_dns_logonly
	elif [ "${ARGUMENT_TLS}" = '1' ] && [ "${ARGUMENT_LOGONLY}" = '1' ]; then
		feature_tls_logonly
	elif [ "${ARGUMENT_TOR}" = '1' ] && [ "${ARGUMENT_LOGONLY}" = '1' ]; then
		feature_tor_logonly
	elif [ "${ARGUMENT_ALL}" = '1' ] && [ "${ARGUMENT_LOGONLY}" = '1' ]; then
		feature_all_logonly
    elif [ "${ARGUMENT_PING}" = '1' ] && [ "${ARGUMENT_CLI}" = '1' ]; then
		feature_ping_cli
    elif [ "${ARGUMENT_PORT}" = '1' ] && [ "${ARGUMENT_CLI}" = '1' ]; then
		feature_port_cli
	elif [ "${ARGUMENT_HTTP}" = '1' ] && [ "${ARGUMENT_CLI}" = '1' ]; then
		feature_http_cli
	elif [ "${ARGUMENT_DNS}" = '1' ] && [ "${ARGUMENT_CLI}" = '1' ]; then
		feature_dns_cli
	elif [ "${ARGUMENT_TLS}" = '1' ] && [ "${ARGUMENT_CLI}" = '1' ]; then
		feature_tls_cli
	elif [ "${ARGUMENT_TOR}" = '1' ] && [ "${ARGUMENT_CLI}" = '1' ]; then
		feature_tor_cli
	elif [ "${ARGUMENT_ALL}" = '1' ] && [ "${ARGUMENT_CLI}" = '1' ]; then
		feature_all_cli
    elif [ "${ARGUMENT_PING}" = '1' ] && [ "${ARGUMENT_TELEGRAM}" = '1' ]; then
		feature_ping_telegram
    elif [ "${ARGUMENT_PORT}" = '1' ] && [ "${ARGUMENT_TELEGRAM}" = '1' ]; then
		feature_port_telegram
	elif [ "${ARGUMENT_HTTP}" = '1' ] && [ "${ARGUMENT_TELEGRAM}" = '1' ]; then
		feature_http_telegram
	elif [ "${ARGUMENT_DNS}" = '1' ] && [ "${ARGUMENT_TELEGRAM}" = '1' ]; then
		feature_dns_telegram
	elif [ "${ARGUMENT_TLS}" = '1' ] && [ "${ARGUMENT_TELEGRAM}" = '1' ]; then
		feature_tls_telegram
	elif [ "${ARGUMENT_TOR}" = '1' ] && [ "${ARGUMENT_TELEGRAM}" = '1' ]; then
		feature_tor_telegram
	elif [ "${ARGUMENT_ALL}" = '1' ] && [ "${ARGUMENT_TELEGRAM}" = '1' ]; then
		feature_all_telegram
    # method list is the default method, so even when no method is given method list is used
	elif [ "${ARGUMENT_PING}" = '1' ]; then
        feature_ping_list
    elif [ "${ARGUMENT_PORT}" = '1' ]; then
        feature_port_list
	elif [ "${ARGUMENT_HTTP}" = '1' ]; then
        feature_http_list
	elif [ "${ARGUMENT_DNS}" = '1' ]; then
        feature_dns_list
	elif [ "${ARGUMENT_TLS}" = '1' ]; then
        feature_tls_list
	elif [ "${ARGUMENT_TOR}" = '1' ]; then
        feature_tor_list
	# options can not be used with a method or feature
    elif [ "${ARGUMENT_CRON}" = '1' ]; then
        option_cron
    elif [ "${ARGUMENT_VERSION}" = '1' ]; then
        option_version
    elif [ "${ARGUMENT_HELP}" = '1' ]; then
        option_help
    # the overview is shown when no arguments were given
    else
        feature_all_list
    fi
}

####################################################################################################
# CALL MAIN FUNCTION
####################################################################################################

uptimebot_main
